#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Sun Sep 27 18:50:15 GMT 2026
android.nonTransitiveRClass=true
kotlin.code.style=official
systemProp.user.language=en
systemProp.user.country=US
ksp.incremental=false
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx1024m -XX\:MaxMetaspaceSize\=256m -Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8 -Duser.language\=en -Duser.country\=US
android.useAndroidX=true
